name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install black ruff pytest
      - name: Lint with Ruff
        run: ruff check src tests
      - name: Format with Black
        run: black --check src tests
      - name: Run tests
        run: PYTHONPATH=src pytest
